# Generated by Django 3.2.18 on 2023-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='friend',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
