# Generated by Django 3.2.18 on 2023-04-17 03:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
