# Generated by Django 3.2.18 on 2023-04-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_menuitem_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='friend',
        ),
    ]
